plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\HP\\OneDrive\\Bureau\\projet flutter\\allo_secours"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/flutter_bootstrap.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/main.dart.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/flutter_service_worker.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]