// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0bLUO4JMEyZ_QiekGIxc6jWBh8Imncng',
    appId: '1:1063798739268:web:fb709f462737885b2e0711',
    messagingSenderId: '1063798739268',
    projectId: 'allo-secours-ec8aa',
    authDomain: 'allo-secours-ec8aa.firebaseapp.com',
    storageBucket: 'allo-secours-ec8aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxbqk-I9btm8hGvrWQkVli9gkNm6YtLS4',
    appId: '1:1063798739268:android:4d84e4f50c3f30592e0711',
    messagingSenderId: '1063798739268',
    projectId: 'allo-secours-ec8aa',
    storageBucket: 'allo-secours-ec8aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsVEub8fq2h4OZQ8LxADDbe-9z8o9aAgc',
    appId: '1:1063798739268:ios:31e66591c7bc348e2e0711',
    messagingSenderId: '1063798739268',
    projectId: 'allo-secours-ec8aa',
    storageBucket: 'allo-secours-ec8aa.firebasestorage.app',
    iosBundleId: 'com.example.alloSecours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsVEub8fq2h4OZQ8LxADDbe-9z8o9aAgc',
    appId: '1:1063798739268:ios:31e66591c7bc348e2e0711',
    messagingSenderId: '1063798739268',
    projectId: 'allo-secours-ec8aa',
    storageBucket: 'allo-secours-ec8aa.firebasestorage.app',
    iosBundleId: 'com.example.alloSecours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0bLUO4JMEyZ_QiekGIxc6jWBh8Imncng',
    appId: '1:1063798739268:web:bfac9b1ee7894d142e0711',
    messagingSenderId: '1063798739268',
    projectId: 'allo-secours-ec8aa',
    authDomain: 'allo-secours-ec8aa.firebaseapp.com',
    storageBucket: 'allo-secours-ec8aa.firebasestorage.app',
  );
}
